#!/usr/bin/perl
#
# hires-date - A high-resolution clock (uses Gtk)
#
# Copyright (c) 2010 nandhp <nandhp@gmail.com>
#
# Licensed under the 2-clause BSD license.
# http://opensource.org/licenses/BSD-2-Clause
#

use Gtk2 qw/-init/;
use Time::HiRes qw/time/;

my $win = Gtk2::Window->new();
my $l = Gtk2::Label->new();
$l->set_size_request(200,-1);
update_clock();
$win->add($l);
$win->show_all;
$win->signal_connect('destroy', sub { Gtk2->main_quit });
Gtk2->main;

sub update_clock {
    my $now = time;
    my $intnow = int($now);
    my $del = ($intnow+1-$now)*1000;
    $del += 1000 if $del < 100;
    Glib::Timeout->add($del,\&update_clock);
    my $str = scalar localtime $intnow;
    $str =~ s/:(\d\d) /sprintf(":%04.1f ",$1+($now-$intnow))/e;
    $l->set_text($str);
    printf "%.6f\n", $now;
    return 0;
}
